version = 1

test_patterns = ["tests/**"]

exclude_patterns = ["*.cpp"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  max_line_length = 88
  type_checker = "mypy"
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true
